# Generated by Django 3.2.25 on 2024-03-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
